#!/usr/bin/env bash

# Copyright 2014 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This is a wrapper around the frontend of autopiper. The frontend is written
# in Clojure and packaged in a JAR, and must be run using the JVM.

# Find the JAR. We look in the current directory first, then
# ../share/autopiper/ next.
MYPATH=$(cd `dirname $0`; pwd)

JAR=""
BASE="autopiper-frontend.jar"
CAND="$MYPATH/$BASE $MYPATH/../share/autopiper/$BASE"
for candidate in $CAND; do
    if [ -e $candidate ]; then
        JAR=$candidate
        break
    fi
done

if [ "$JAR" = "" ]; then
    echo Could not find ${BASE}. Please ensure that this
    echo file exists in one of the following directories:
    echo $CAND
    exit 1
fi

if [ "$JAVA" = "" ]; then
    JAVA=java
fi

$JAVA -jar $JAR "$@"
